# Generated by Django 2.0.2 on 2020-03-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='Profile',
        ),
    ]
